# Generated by Django 5.1.6 on 2025-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('urgent_important', 'Urgent & Important'), ('important_not_urgent', 'Important mais pas Urgent'), ('urgent_not_important', 'Urgent mais pas Important'), ('not_urgent_not_important', 'Ni Urgent ni Important')], max_length=30)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
